pipeline:
  build_docker_image:
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t drone .

  run_drone:
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker run --rm drone

  latest_image_to_quay:
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="${DOCKER_USERNAME}" -p=${DOCKER_PASSWORD} hub.docker.com
      - docker tag drone hub.docker.com/forbesj/drone:${DRONE_COMMIT_SHA}
      - docker push hub.docker.com/forbesj/ubuntu:${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master

  tag_image_to_quay:
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="${DOCKER_ARTIFACTORY_USERNAME}" -p=${DOCKER_ARTIFACTORY_PASSWORD} ${ARTIFACTORY_DNS}:5001
      - docker tag drone ${ARTIFACTORY_DNS}:5001/drone:${DRONE_COMMIT_SHA}
      - docker push ${ARTIFACTORY_DNS}:5001/drone:${DRONE_COMMIT_SHA}
    when:
      event: tag

services:
  dind:
    image: docker:1.12-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
